/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uaspbo2.uas_pbo2_19710116;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import com.uaspbo2.uas_pbo2_19710116.Koneksi;
import java.io.File;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.sql.DriverManager;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;

/**
 *
 * @author mikah
 */
public class MobilView extends javax.swing.JInternalFrame {

    /**
     * Creates new form MobilView
     */
    public MobilView() {
        initComponents();
        ulang();
        cekPemakai();
    }

    PreparedStatement pst;
    ResultSet rs;
    Connection conn = new Koneksi().getKoneksi();
    String id, sql;

    private void cekPemakai() {
        String hostname1 = "Unknown";

        try {
            InetAddress addr;
            addr = InetAddress.getLocalHost();
            hostname1 = addr.getHostName();
        } catch (UnknownHostException ex) {
            System.out.println("Hostname can not be resolved");
        }
    }

    private void ulang() {
        ePlat.setText("");
        eMerek.setText("");
        eModel.setText("");
        eWarna.setText("");
        eHarga.setText("");
        cbTransmisi.setSelectedIndex(0);
        cbStatus.setSelectedIndex(0);
        eCari.setText("");
        tampilData();
        bSimpan.setEnabled(true);
        bUbah.setEnabled(false);
        bHapus.setEnabled(false);
        id = "";
    }

    private void tampilData() {
        try {
            String[] judul = {"ID", "No. Plat", "Merek", "Model", "Warna", "Transmisi", "Harga", "Status"};
            DefaultTableModel dtm = new DefaultTableModel(null, judul);
            tMobil.setModel(dtm);
            tMobil.getColumnModel().getColumn(0).setPreferredWidth(5);

            if (eCari.getText().isEmpty()) {
                sql = "select * from mobil";
                pst = conn.prepareStatement(sql);
            } else {
                sql = "select * from mobil where merek like '%" + eCari.getText() + "%' or model like '%" + eCari.getText() + "%'";
                pst = conn.prepareStatement(sql);
            }
            rs = pst.executeQuery();
            while (rs.next()) {
                DecimalFormat myFormatter = new DecimalFormat("#,###");
                String str = myFormatter.format(rs.getDouble(7));
                String[] data = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5),
                    rs.getString(6), str, rs.getString(8)};
                dtm.addRow(data);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ePlat = new javax.swing.JTextField();
        eMerek = new javax.swing.JTextField();
        eModel = new javax.swing.JTextField();
        eWarna = new javax.swing.JTextField();
        cbTransmisi = new javax.swing.JComboBox<>();
        eHarga = new javax.swing.JTextField();
        cbStatus = new javax.swing.JComboBox<>();
        bSimpan = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tMobil = new javax.swing.JTable();
        bKeluar = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        eCari = new javax.swing.JTextField();
        bCetak = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORM MOBIL");

        jLabel2.setText("No. Plat");

        jLabel3.setText("Merek");

        jLabel4.setText("Model");

        jLabel5.setText("Warna");

        jLabel6.setText("Transmisi");

        jLabel7.setText("Harga Mobil");

        jLabel8.setText("Status");

        cbTransmisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matic", "Manual" }));

        eHarga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                eHargaFocusLost(evt);
            }
        });
        eHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                eHargaKeyPressed(evt);
            }
        });

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tersedia", "Terjual" }));

        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });

        tMobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "No. Plat", "Merek", "Model", "Warna", "Transmisi", "Harga", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tMobil.getTableHeader().setReorderingAllowed(false);
        tMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tMobilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tMobil);
        if (tMobil.getColumnModel().getColumnCount() > 0) {
            tMobil.getColumnModel().getColumn(0).setResizable(false);
            tMobil.getColumnModel().getColumn(1).setResizable(false);
            tMobil.getColumnModel().getColumn(2).setResizable(false);
            tMobil.getColumnModel().getColumn(3).setResizable(false);
            tMobil.getColumnModel().getColumn(4).setResizable(false);
            tMobil.getColumnModel().getColumn(5).setResizable(false);
            tMobil.getColumnModel().getColumn(6).setResizable(false);
            tMobil.getColumnModel().getColumn(7).setResizable(false);
        }

        bKeluar.setText("Keluar");
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });

        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        jLabel9.setText("Cari Mobil");

        eCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                eCariKeyReleased(evt);
            }
        });

        bCetak.setText("Cetak");
        bCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(eWarna, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(eModel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eMerek, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ePlat, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbTransmisi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eHarga)
                            .addComponent(cbStatus, 0, 141, Short.MAX_VALUE)
                            .addComponent(eCari))
                        .addGap(87, 87, 87))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(bSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(bUbah)
                        .addGap(18, 18, 18)
                        .addComponent(bHapus)
                        .addGap(18, 18, 18)
                        .addComponent(bReset)
                        .addGap(18, 18, 18)
                        .addComponent(bCetak)
                        .addGap(18, 18, 18)
                        .addComponent(bKeluar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ePlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTransmisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(eMerek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(eHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(eModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(eWarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(eCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSimpan)
                    .addComponent(bUbah)
                    .addComponent(bKeluar)
                    .addComponent(bHapus)
                    .addComponent(bReset)
                    .addComponent(bCetak))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        if (ePlat.getText().isEmpty() || eMerek.getText().isEmpty() || eModel.getText().isEmpty()
                || eWarna.getText().isEmpty() || eHarga.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Field Belum Terisi Lengkap");
        } else {
            try {
                sql = "insert into mobil values (?,?,?,?,?,?,?,?)";
                pst = conn.prepareStatement(sql);
                pst.setString(1, null);
                pst.setString(2, ePlat.getText());
                pst.setString(3, eMerek.getText());
                pst.setString(4, eModel.getText());
                pst.setString(5, eWarna.getText());
                pst.setString(6, cbTransmisi.getSelectedItem().toString());
                pst.setBigDecimal(7, new BigDecimal(eHarga.getText().replaceAll("\\D+", "")));
                pst.setString(8, cbStatus.getSelectedItem().toString());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                ulang();
            } catch (SQLException ex) {
                Logger.getLogger(MobilView.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void eCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eCariKeyReleased
        tampilData();
    }//GEN-LAST:event_eCariKeyReleased

    private void tMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tMobilMouseClicked
        int baris = tMobil.getSelectedRow();
        id = tMobil.getValueAt(baris, 0).toString();
        if (!id.isEmpty()) {
            ePlat.setText(tMobil.getValueAt(baris, 1).toString());
            eMerek.setText(tMobil.getValueAt(baris, 2).toString());
            eModel.setText(tMobil.getValueAt(baris, 3).toString());
            eWarna.setText(tMobil.getValueAt(baris, 4).toString());
            cbTransmisi.setSelectedItem(tMobil.getValueAt(baris, 5).toString());
            eHarga.setText(tMobil.getValueAt(baris, 6).toString());
            cbStatus.setSelectedItem(tMobil.getValueAt(baris, 7).toString());
            bSimpan.setEnabled(false);
            bUbah.setEnabled(true);
            bHapus.setEnabled(true);
        }
    }//GEN-LAST:event_tMobilMouseClicked

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        ulang();
    }//GEN-LAST:event_bResetActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        int konf = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menghapus data ini?",
                "HAPUS DATA", JOptionPane.YES_NO_OPTION);
        if (konf == 0) {
            try {
                sql = "delete from mobil where id=?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                ulang();
            } catch (SQLException ex) {
                Logger.getLogger(MobilView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_bHapusActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        dispose();
        ulang();
    }//GEN-LAST:event_bKeluarActionPerformed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        int konf = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin mengubah data ini?",
                "UBAH DATA", JOptionPane.YES_NO_OPTION);
        if (konf == 0) {
            try {
                sql = "update mobil set no_plat=?, merek=?, model=?, warna=?, transmisi=?, "
                        + "harga_mobil=?, status=? where id=?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, ePlat.getText());
                pst.setString(2, eMerek.getText());
                pst.setString(3, eModel.getText());
                pst.setString(4, eWarna.getText());
                pst.setString(5, cbTransmisi.getSelectedItem().toString());
                pst.setString(6, eHarga.getText().replaceAll("\\D+", ""));
                pst.setString(7, cbStatus.getSelectedItem().toString());
                pst.setString(8, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
                ulang();
            } catch (SQLException ex) {
                Logger.getLogger(MobilView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_bUbahActionPerformed

    private void eHargaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eHargaKeyPressed

    }//GEN-LAST:event_eHargaKeyPressed

    private void eHargaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_eHargaFocusLost
        DecimalFormat myFormatter = new DecimalFormat("#,###");
        String fix = myFormatter.format(Double.parseDouble(eHarga.getText()));
        eHarga.setText(fix);
    }//GEN-LAST:event_eHargaFocusLost

    private void bCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCetakActionPerformed
        try {
            String filetoFill = "./src/main/java/com/uaspbo2/uas_pbo2_19710116/rMobil.jasper";
            JasperPrint jp = JasperFillManager.fillReport(filetoFill, null, conn);
            JasperViewer.viewReport(jp, false);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_bCetakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCetak;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bUbah;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JComboBox<String> cbTransmisi;
    private javax.swing.JTextField eCari;
    private javax.swing.JTextField eHarga;
    private javax.swing.JTextField eMerek;
    private javax.swing.JTextField eModel;
    private javax.swing.JTextField ePlat;
    private javax.swing.JTextField eWarna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tMobil;
    // End of variables declaration//GEN-END:variables
}
