/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uaspbo2.uas_pbo2_19710116;

import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author mikah
 */
public class PembelianView extends javax.swing.JInternalFrame {

    /**
     * Creates new form PembelianView
     */
    public PembelianView() {
        initComponents();
        eIdPembeli.setVisible(false);
        data_pembeli();
        ulang();
        JTextFieldDateEditor editor = (JTextFieldDateEditor) jDateChooser1.getDateEditor();
        editor.setEnabled(false);
    }

    PreparedStatement pst;
    ResultSet rs;
    Connection conn = new Koneksi().getKoneksi();
    DecimalFormat myFormatter = new DecimalFormat("#,###");
    String id, sql;

    private void hitung() {
        int harga = Integer.valueOf(eHarga.getText().replaceAll("\\D+", ""));
        int bayar = Integer.valueOf(eBayar.getText().replaceAll("\\D+", ""));
        int sisa = harga - bayar;
        if (sisa < 0) {
            JOptionPane.showMessageDialog(null, "Jumlah Bayar Melebihi Ketentuan Harga");
            eBayarMouseClicked(null);
        } else {
            eSisa.setText(myFormatter.format(sisa));
            eBayar.setText(myFormatter.format(bayar));
        }
    }

    private void ulang() {
        cbPembeli.setSelectedIndex(0);
        jDateChooser1.setDate(new java.util.Date());
        eIdMobil.setText("");
        eMerek.setText("");
        eModel.setText("");
        eWarna.setText("");
        eTransmisi.setText("");
        eHarga.setText("0");
        cbJenis.setSelectedIndex(0);
        cbJenis.setEnabled(false);
        eBayar.setText("0");
        eBayar.setEnabled(false);
        eSisa.setText("0");
        eCari.setText("");
        bSimpan.setEnabled(true);
        bUbah.setEnabled(false);
        bHapus.setEnabled(false);
        tampilData();
    }

    private void tampilData() {
        try {
            String[] judul = {"ID", "Tanggal Pembelian", "Jenis Pembayaran", "ID Pembeli", "ID Mobil",
                "Jumlah Terbayar", "Sisa Bayar"};
            DefaultTableModel dtm = new DefaultTableModel(null, judul);
            tPembelian.setModel(dtm);
            tPembelian.getColumnModel().getColumn(0).setPreferredWidth(30);

            if (eCari.getText().isEmpty()) {
                sql = "select * from pembelian";
                //sql = "select p.*, m.* from pembelian p inner join mobil m on p.mobil_id = m.id";
                pst = conn.prepareStatement(sql);
            } else {
                sql = "select * from pembelian where id like '%" + eCari.getText() + "%'";
                pst = conn.prepareStatement(sql);
            }
            rs = pst.executeQuery();
            while (rs.next()) {
                DecimalFormat myFormatter = new DecimalFormat("#,###");
                DateFormat df = new SimpleDateFormat("dd-MM-yyyy");
                String str6 = myFormatter.format(rs.getDouble(6));
                String str7 = myFormatter.format(rs.getDouble(7));
                String str2 = df.format(rs.getDate(2));
                String[] data = {rs.getString(1), str2, rs.getString(3), rs.getString(4), rs.getString(5),
                    str6, str7};
                dtm.addRow(data);
            }
            jDateChooser1.setDate(new java.util.Date());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }

    private void data_pembeli() {
        try {
            cbPembeli.removeAllItems();
            cbPembeli.addItem("");
            sql = "SELECT nama_lengkap FROM pembeli";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                cbPembeli.addItem(rs.getString(1));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbPembeli = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        eIdMobil = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        eMerek = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        eModel = new javax.swing.JTextField();
        eWarna = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        eTransmisi = new javax.swing.JTextField();
        eHarga = new javax.swing.JTextField();
        bCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tPembelian = new javax.swing.JTable();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        cbJenis = new javax.swing.JComboBox<>();
        eBayar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        eSisa = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        eCari = new javax.swing.JTextField();
        bUbah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();
        bUlang = new javax.swing.JButton();
        bCetak = new javax.swing.JButton();
        eIdPembeli = new javax.swing.JTextField();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Form Entry Transaksi");

        cbPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPembeliActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama Pembeli");

        jLabel3.setText("Kode Mobil");

        eIdMobil.setEditable(false);

        jLabel4.setText("Merek Mobil");

        eMerek.setEditable(false);

        jLabel5.setText("Model Mobil");

        jLabel6.setText("Warna Mobil");

        eModel.setEditable(false);

        eWarna.setEditable(false);

        jLabel7.setText("Transmisi");

        jLabel8.setText("Harga");

        eTransmisi.setEditable(false);

        eHarga.setEditable(false);
        eHarga.setText("0");

        bCari.setText("Cari");
        bCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCariActionPerformed(evt);
            }
        });

        tPembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tanggal Pembelian", "Jenis Pembayaran", "ID Pembeli", "ID Mobil", "Terbayar", "Sisa Bayar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tPembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tPembelianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tPembelian);
        if (tPembelian.getColumnModel().getColumnCount() > 0) {
            tPembelian.getColumnModel().getColumn(0).setResizable(false);
            tPembelian.getColumnModel().getColumn(0).setPreferredWidth(30);
            tPembelian.getColumnModel().getColumn(1).setResizable(false);
            tPembelian.getColumnModel().getColumn(2).setResizable(false);
            tPembelian.getColumnModel().getColumn(3).setResizable(false);
            tPembelian.getColumnModel().getColumn(4).setResizable(false);
            tPembelian.getColumnModel().getColumn(5).setResizable(false);
            tPembelian.getColumnModel().getColumn(6).setResizable(false);
        }

        jDateChooser1.setDateFormatString("dd MMM yyyy");
        jDateChooser1.setFocusable(false);

        jLabel9.setText("Jenis Pembayaran");

        cbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kredit", "Cash" }));
        cbJenis.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbJenisItemStateChanged(evt);
            }
        });
        cbJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJenisActionPerformed(evt);
            }
        });
        cbJenis.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbJenisPropertyChange(evt);
            }
        });

        eBayar.setText("0");
        eBayar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                eBayarFocusLost(evt);
            }
        });
        eBayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eBayarMouseClicked(evt);
            }
        });
        eBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eBayarActionPerformed(evt);
            }
        });
        eBayar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                eBayarPropertyChange(evt);
            }
        });
        eBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                eBayarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                eBayarKeyReleased(evt);
            }
        });

        jLabel11.setText("Bayar");

        jLabel12.setText("Sisa Bayar");

        eSisa.setEditable(false);
        eSisa.setText("0");

        jLabel13.setText("Cari Transaksi");

        eCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                eCariKeyReleased(evt);
            }
        });

        bUbah.setText("Ubah");
        bUbah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });

        bHapus.setText("Hapus");
        bHapus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bSimpan.setText("Simpan");
        bSimpan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bKeluar.setText("Keluar");
        bKeluar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });

        bUlang.setText("Ulang");
        bUlang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bUlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUlangActionPerformed(evt);
            }
        });

        bCetak.setText("Cetak");
        bCetak.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCetakActionPerformed(evt);
            }
        });

        eIdPembeli.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbPembeli, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(eIdMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bCari, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(eMerek))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel6))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(eModel, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                                    .addComponent(eWarna)))
                                            .addComponent(eIdPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(eHarga, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(eTransmisi, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(bSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(bUlang, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel13)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(eCari, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addComponent(bCetak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(bUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(bHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(bKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(cbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(eBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(eSisa, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(eIdPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(eIdMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bCari))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(eMerek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(eModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(eWarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(eTransmisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(eHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(eCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(eBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bUbah)
                    .addComponent(bHapus)
                    .addComponent(bSimpan))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eSisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(bKeluar)
                    .addComponent(bUlang)
                    .addComponent(bCetak))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
        int konf = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menghapus data ini?",
                "HAPUS DATA", JOptionPane.YES_NO_OPTION);
        if (konf == 0) {
            try {
                sql = "delete from pembelian where id=?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                ulang();
            } catch (SQLException ex) {
                Logger.getLogger(MobilView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_bHapusActionPerformed

    private void cbPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPembeliActionPerformed
        try {
            pst = conn.prepareStatement("SELECT id from pembeli WHERE nama_lengkap=?");
            pst.setString(1, cbPembeli.getSelectedItem().toString());
            rs = pst.executeQuery();
            if (rs.next()) {
                eIdPembeli.setText(rs.getString(1));
            }
            if (cbPembeli.getSelectedItem().toString().isEmpty()) {
                eIdPembeli.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(PembelianView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbPembeliActionPerformed

    private void bCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCariActionPerformed
        CariMobilView cariMobilView = new CariMobilView(null, true);
        cariMobilView.setVisible(true);
    }//GEN-LAST:event_bCariActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_bKeluarActionPerformed

    private void cbJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisActionPerformed
        if (cbJenis.getSelectedIndex() == 1) {
            eBayar.setEnabled(true);
        } else if (cbJenis.getSelectedIndex() == 0) {
            eBayar.setEnabled(false);
        }
    }//GEN-LAST:event_cbJenisActionPerformed

    private void bUlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUlangActionPerformed
        ulang();
    }//GEN-LAST:event_bUlangActionPerformed

    private void eBayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eBayarKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_eBayarKeyReleased

    private void eBayarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_eBayarFocusLost
        //hitung();
    }//GEN-LAST:event_eBayarFocusLost

    private void eBayarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_eBayarPropertyChange

    }//GEN-LAST:event_eBayarPropertyChange

    private void cbJenisPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbJenisPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJenisPropertyChange

    private void cbJenisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbJenisItemStateChanged
        if (cbJenis.getSelectedIndex() == 0) {
            eBayar.setText("0");
        }
        hitung();
    }//GEN-LAST:event_cbJenisItemStateChanged

    private void eBayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eBayarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            hitung();
        }
    }//GEN-LAST:event_eBayarKeyPressed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
        if (cbPembeli.getSelectedItem().toString().isEmpty() || eIdMobil.getText().isEmpty() || eSisa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Field Belum Terisi Lengkap");
        } else {
            try {
                sql = "insert into pembelian values (?,?,?,?,?,?,?)";
                pst = conn.prepareStatement(sql);
                pst.setString(1, null);
                pst.setDate(2, new java.sql.Date(jDateChooser1.getDate().getTime()));
                pst.setString(3, cbJenis.getSelectedItem().toString());
                pst.setString(4, eIdPembeli.getText());
                pst.setString(5, eIdMobil.getText());
                pst.setBigDecimal(6, new BigDecimal(eBayar.getText().replaceAll("\\D+", "")));
                pst.setBigDecimal(7, new BigDecimal(eSisa.getText().replaceAll("\\D+", "")));
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                ulang();
            } catch (SQLException ex) {
                Logger.getLogger(MobilView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void eBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eBayarActionPerformed

    }//GEN-LAST:event_eBayarActionPerformed

    private void eBayarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eBayarMouseClicked
        eBayar.selectAll();
    }//GEN-LAST:event_eBayarMouseClicked

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        // TODO add your handling code here:
        int konf = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin mengubah data ini?",
                "UBAH DATA", JOptionPane.YES_NO_OPTION);
        if (konf == 0) {
            try {
                sql = "update pembelian set tanggal_pembelian=?, jenis_pembayaran=?, pembeli_id=?, mobil_id=?,"
                        + "jumlah_bayar=?, sisa_bayar=? where id=?";
                pst = conn.prepareStatement(sql);
                pst.setDate(1, new java.sql.Date(jDateChooser1.getDate().getTime()));
                pst.setString(2, cbJenis.getSelectedItem().toString());
                pst.setString(3, eIdPembeli.getText());
                pst.setString(4, eIdMobil.getText());
                pst.setBigDecimal(5, new BigDecimal(eBayar.getText().replaceAll("\\D+", "")));
                pst.setBigDecimal(6, new BigDecimal(eSisa.getText().replaceAll("\\D+", "")));
                pst.setString(7, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
                ulang();
            } catch (SQLException ex) {
                Logger.getLogger(PembeliView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_bUbahActionPerformed

    private void tPembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tPembelianMouseClicked
        // TODO add your handling code here:
        cbJenis.setEnabled(true);
        bUbah.setEnabled(true);
        bHapus.setEnabled(true);
        int baris = tPembelian.getSelectedRow();
        id = tPembelian.getValueAt(baris, 0).toString();
        if (!id.isEmpty()) {
            try {
                jDateChooser1.setDate(new SimpleDateFormat("dd-MM-yyyy").parse(tPembelian.getValueAt(baris, 1).toString()));
                cbJenis.setSelectedItem(tPembelian.getValueAt(baris, 2).toString());
                eIdPembeli.setText(tPembelian.getValueAt(baris, 3).toString());
                eIdMobil.setText(tPembelian.getValueAt(baris, 4).toString());
                eBayar.setText(tPembelian.getValueAt(baris, 5).toString());
                eSisa.setText(tPembelian.getValueAt(baris, 6).toString());
                bSimpan.setEnabled(false);
                bUbah.setEnabled(true);
                bHapus.setEnabled(true);
            } catch (ParseException ex) {
                Logger.getLogger(PembelianView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        sql = "select * from pembeli where id=?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, eIdPembeli.getText());
            rs = pst.executeQuery();
            while (rs.next()) {
                cbPembeli.setSelectedItem(rs.getString("nama_lengkap"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(PembelianView.class.getName()).log(Level.SEVERE, null, ex);
        }
        sql = "select * from mobil where id=?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, eIdMobil.getText());
            rs = pst.executeQuery();
            while (rs.next()) {
                eMerek.setText(rs.getString(3));
                eModel.setText(rs.getString(4));
                eWarna.setText(rs.getString(5));
                eTransmisi.setText(rs.getString(6));
                eHarga.setText(myFormatter.format(rs.getDouble(7)));
            }
        } catch (SQLException ex) {
            Logger.getLogger(PembelianView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tPembelianMouseClicked

    private void bCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCetakActionPerformed
        // TODO add your handling code here:
        try {
            String filetoFill="./src/main/java/com/uaspbo2/uas_pbo2_19710116/rPembelian.jasper";
            JasperPrint jp=JasperFillManager.fillReport(filetoFill, null, conn);
            JasperViewer.viewReport(jp,false);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_bCetakActionPerformed

    private void eCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eCariKeyReleased
        tampilData();
    }//GEN-LAST:event_eCariKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCari;
    private javax.swing.JButton bCetak;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bUbah;
    private javax.swing.JButton bUlang;
    public static javax.swing.JComboBox<String> cbJenis;
    private javax.swing.JComboBox<String> cbPembeli;
    public static javax.swing.JTextField eBayar;
    private javax.swing.JTextField eCari;
    public static javax.swing.JTextField eHarga;
    public static javax.swing.JTextField eIdMobil;
    private javax.swing.JTextField eIdPembeli;
    public static javax.swing.JTextField eMerek;
    public static javax.swing.JTextField eModel;
    public static javax.swing.JTextField eSisa;
    public static javax.swing.JTextField eTransmisi;
    public static javax.swing.JTextField eWarna;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tPembelian;
    // End of variables declaration//GEN-END:variables
}
